#!/bin/bash
# this test script is applicable to 
# MX-10261:Deliever message when autoReplyStartDate and autoReplyStopDate unset::Expect autoreply success on testlink 

#define accounts variables
user1=ar$(echo $RANDOM)
user2=ar$(echo $RANDOM)

autoreplymode="echo"

#define clean_account function
function clean_accounts ()
{
		echo "##########  doing some clear job ..."
		
		#delete accounts
		mos_delete_user.sh ${MXOS1_HOST_IP}  $MXOS1__PORT $user1@$newdomain
		mos_delete_user.sh ${MXOS1_HOST_IP}  $MXOS1__PORT $user2@$defaultdomain
		mos_delete_domain.sh ${MXOS1_HOST_IP}  $MXOS1__PORT $newdomain
}

trap clean_accounts SIGHUP SIGINT SIGTERM

#1 clear mta.log and other tmp files
echo "########## 1 Clear mta.log using expect tool ..."
expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"> ~/log/mta.log"

#clear other tmp log files
rm expect*.log 
rm imapfetch*.log
rm send*.log
	
#2 create accounts user1@$defaultdomain and user2@$defaultdomain
echo "########## 2 Accounts provision ..."
#create domain
mos_create_domain.sh ${MXOS1_HOST_IP}  $MXOS1__PORT $newdomain
mos_create_user.sh  ${MXOS1_HOST_IP}  $MXOS1__PORT $user1@$newdomain $passwd
mos_create_user.sh  ${MXOS1_HOST_IP}  $MXOS1__PORT $user2@$defaultdomain $passwd

#3 configure user2 to proper autoreply mode
echo "########## 3 Configure user2 to echo autoreply mode using expect tool ..."

expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"echo 'internal:' >data.txt" \
"echo 'Echo,This is an autoreply message for internal senders!' >>data.txt" \
"echo 'external:' >>data.txt" \
"echo 'Echo,This is an external autoreply message for external senders!' >>data.txt" \
"autoreplyctrl ${user2}@$defaultdomain $autoreplymode data.txt none none"

count=$(grep  -i "AutoReply data updated Successfully"  expect.log|wc -l)
if [[ "$count" -eq "1" ]];then
	echo -e "\033[32m##########3 Congifuration successfully\033[0m"
else
	echo -e "\033[31m##########3 Configuration failed,please check maunually!Exiting now ...\033[0m"
	clean_accounts
	exit 2
fi

# 4 deliever 1 message from user1 to user2, we expect that will have a autoreplied message (with origin message attached)in inbox of user1
echo "##########4 delieber 1 message from user1 to user2 ..."
#create message body
echo "Subject: test message about autoreply feature" >send.data
echo "To:$user2@$defaultdomain" >>send.data
echo >>send.data
echo "Echo,This ia a wonderful world!!" >>send.data

sendmail.pl  $MX1_HOST_IP1 $MX1_SMTP_PORT $user1@$newdomain $user2@$defaultdomain  <send.data >send.log 
count=$(grep "250 Message received" send.log|wc -l)
if [[ "$count" -eq "1" ]]
then
  echo -e "\033[32m########## 4 Message Deliver successfully, we can continue now\033[0m"
else
	echo -e "\033[31m########## 4 Message Deliver failed,please check manually,Exiting now ...\033[0m"
	cat send.log 
	clean_accounts
	exit 3
fi

#5 check mta.log, make sure autoreply flag "autoreplied" exist:
echo "########## 5 Check mta.log using expect tool ..."
expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"cat log/mta.log"

count=$(grep  -i "autoreplied"  expect.log|wc -l)	
count1=$(grep -i "delivered" expect.log |wc -l)
if [[ "$count" -eq "1" && "$count1" -eq "2" ]];then
	echo -e "\033[32m##########5 Autoreply messaeg delievered successfully!!\033[0m"
else
	echo -e "\033[31m##########5 Autoreply messaeg delievered failed!Please check manually,Exiting now ...\033[0m"
	clean_accounts
	exit 4
fi 

# 6 check autoreplied message in inbox of user1
echo "########## 5 check autoreplied message in inbox of user1 ..."
imapmail.pl   $MX1_HOST_IP1 $MX1_IMAP_PORT $user1 $passwd inbox 2 >imapfetch.log
cat imapfetch.log
count=$(grep "Echo,This is an external autoreply message for external senders!" imapfetch.log|wc -l)
count1=$(grep "Echo,This ia a wonderful world!!" imapfetch.log|wc -l)
if [[ "$count" -eq	 "1" && "$count1" -eq "1" ]];then
		echo -e "\033[32m##########6 Check autoreplied messaege successfully!!\033[0m"
		log_pass "AutoReply in $autoreplymode mode without start/stop date for external sender test success!"
else
		echo -e "\033[31m##########6 Check autoreplied messaege failed!Please checl manually,Exiting now ...\033[0m"
		log_fail "AutoReply in $autoreplymode mode without start/stop date for external sender test failed!"
		clean_accounts
		exit 5
fi
#delete all accounts if all works fine.
clean_accounts