#!/bin/bash

expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"ls -al"                                                                           \
cal                                                                                \
date                                                                               \
"df -h"                                                                            \
ps
