#!/bin/bash

expect.exp 50 "10.49.58.239" root letmein imail \
"ls -al"                                        \
cal                                             \
date                                            \
"df -h"                                         \
ps
