#!/bin/bash


#Result=1_by_fefault
Result=1

#body preview key enable	
set_config_keys "/*/common/enableXFIRSTLINE" "true"

#create test account
Sanityuser=test$(echo $RANDOM)
account_create_fn $Sanityuser
imboxstats $Sanityuser@openwave.com &>accountexist.tmp
ec=$(grep -i "Unable to get mailbox" accountexist.tmp |wc -l)
if [ "$ec" -eq 1 ];then
	account_create_fn $Sanityuser
fi

immsgdelete  $Sanityuser@openwave.com  -all


# Running Test.sh


#deliever 2 messages  ro mailbox
$smpl    -u  $Sanityuser@openwave.com -c 3   UTF8_body_equals_80_CTE_base64.txt
imap_uid_fetch "$Sanityuser" "1001:1002" "firstline"     
firstlinedata_count=`grep "qwe wwqe، ويمكن تح No boweq dy! いくつにな  我们是中国人，xx\")"   imapuidfetch.tmp |wc -l`
echo "########## firstlinedata_count=$firstlinedata_count"  >>debug.log
echo "########## Result=$Result"  >>debug.log
if [ $firstlinedata_count -eq 2 -a $Result -eq 0 ];then
	prints "IMAP:Body_preview_UTF8_body_equals_80_CTE_base64_uid_range test successfully!"  "IMAP:Body_preview_UTF8_body_equals_80_CTE_base64_uid_range"  2
	Result=0
else
  prints "IMAP:Body_preview_UTF8_body_equals_80_CTE_base64_uid_range test failed!"  "IMAP:Body_preview_UTF8_body_equals_80_CTE_base64_uid_range"  1
  Result=1
fi
summary "IMAP:Body_preview_UTF8_body_equals_80_CTE_base64_uid_range" $Result

# Running Cleanup.sh
#delete test acocunt
account_delete_fn $Sanityuser


#body preview key disable	
set_config_keys "/*/common/enableXFIRSTLINE" "false"

