#!/bin/bash

#Testing xhread command in shared-folder

domain=dom$$.dom
user1name=user1@$domain
user2name=user2@$domain
password=p

if [ "$MX1_HOST" = "nohost.invalid" ]; then
        log_skip "MX not installed"
        exit 0
fi

if [ "$MXOS1_HOST_IP" = "" ] || [ "$MXOS1_HOST_IP" = "nohost.invalid" ]; then
        log_skip "MXOS not installed"
        exit 0
fi

run_cmd()
{
  mXcmd=$1
  #ssh -o BatchMode=yes $MX1_USER@$MX1_HOST_IP $mXcmd
  ssh root@${MX1_HOST_IP} $mXcmd
  sleep 1
}

testIMAP()
{
username=$1
cmd=$2
./imaplist.pl ${MX1_HOST} ${MX1_IMAP_PORT} $username p "$cmd" > imaplist.out

shift
for key in "$@"
do
if grep "$key" imaplist.out
then
    log_pass "$cmd OK"
else
    cat imaplist.out
    log_fail "$cmd failed"
fi
done
}

cleanup()
{
        mos_delete_user.sh $MXOS1_HOST_IP $MXOS1_PORT $user1name
        mos_delete_user.sh $MXOS1_HOST_IP $MXOS1_PORT $user2name
        mos_delete_domain.sh $MXOS1_HOST_IP $MXOS1_PORT $domain
}

#create domain
curl -X PUT -v -d type=local http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/domain/v2/$domain
#Create User
curl -X PUT -v -d email=user1@$domain -d password=p -d cosId=default http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/user1@$domain
curl -X PUT -v -d email=user2@$domain -d password=p -d cosId=default http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/user2@$domain


cmd="su - ${MX1_USER} -c \"imconfcontrol -install -keys \"/*/imapserv/enableTHREAD=true\"\""
run_cmd "$cmd"

cmd="su - ${MX1_USER} -c \"imconfcontrol -install -keys \"/*/common/enableXFIRSTLINE=true\"\""
run_cmd "$cmd"

cmd="su - ${MX1_USER} -c \"imconfcontrol -install -keys \"/*/common/enableXTHREAD=true\"\""
run_cmd "$cmd"

cmd="su - ${MX1_USER} -c \"imconfcontrol -install -keys \"/*/imapserv/recentParticipantListCount=50\"\""
run_cmd "$cmd"

#create folder
FOLDER=aaaa
testIMAP $user1name "create $FOLDER" "OK CREATE completed"

sleep 2

#shared folder
curl -X PUT -v -H "Content-Type: application/x-www-form-urlencoded" http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/$user1name/folders/$FOLDER/share/$user2name > put.log 2>&1

grep -i "HTTP/1.1 200 OK" put.log
if (( $? == 0 ));then
    log_pass "Shared folder successfully"
else
    log_fail "Shared folder failed"
fi

#send mail from user1 to user2
subject=test$$
for(( i=0; i<5; i++ ))
do

sendmail.pl $MX1_HOST $MX1_SMTP_PORT $user1name $user2name <<- EOF
Subject: ${subject}$i

This is a test mail.

EOF
sleep 3
done


testIMAP $user2name "SELECT INBOX" "6 EXISTS"

#Test thread command in shared-folder
expect << EOF
spawn telnet $MX1_HOST $MX1_IMAP_PORT
expect "OK IMAP4 server"
send "a login $user2name $password\r"
expect "OK LOGIN completed"
send "a select INBOX\r"
expect "2 EXISTS"
send "a move 2:6 $user1name-$FOLDER\r"
expect "MOVE completed"
send "a select $user1name-$FOLDER\r"
expect "SELECT completed"
send "a UID X-THREAD (PARTICIPANTS) UTF-8 ALL\r"
expect "X-THREAD completed"
send "a logout\r"
expect "LOGOUT completed"
EOF


#UnSharedFolder
curl -X DELETE -v -H "Content-Type: application/x-www-form-urlencoded" http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/$user1name/folders/$FOLDER/share/$user2name > del.log 2>&1

grep -i "HTTP/1.1 200 OK" del.log
if (( $? == 0 ));then
    log_pass "unshared folder successfully"
else
    log_fail "unshared folder failed"
fi


#clean up
cmd="su - ${MX1_USER} -c \"imconfcontrol -install -keys \"/*/common/enableXFIRSTLINE=false\"\""
run_cmd "$cmd"

cmd="su - ${MX1_USER} -c \"imconfcontrol -install -keys \"/*/common/enableXTHREAD=false\"\""
run_cmd "$cmd"

rm -rf imaplist.out
rm -rf put.log
rm -rf del.log
cleanup





