#!/bin/bash

#Move messages in sharedFolder
domain=dom$$.dom
user1name=user1@$domain
user2name=user2@$domain
password=p

if [ "$MX1_HOST" = "nohost.invalid" ]; then
        log_skip "MX not installed"
        exit 0
fi

if [ "$MXOS1_HOST_IP" = "" ] || [ "$MXOS1_HOST_IP" = "nohost.invalid" ]; then
        log_skip "MXOS not installed"
        exit 0
fi

testIMAP()
{
username=$1
cmd=$2
./imaplist.pl ${MX1_HOST} ${MX1_IMAP_PORT} $username p "$cmd" > imaplist.out

shift
for key in "$@"
do
if grep "$key" imaplist.out
then
    log_pass "$cmd OK"
else
    cat imaplist.out
    log_fail "$cmd failed"
fi
done
}

cleanup()
{
        mos_delete_user.sh $MXOS1_HOST_IP $MXOS1_PORT $user1name
        mos_delete_user.sh $MXOS1_HOST_IP $MXOS1_PORT $user2name
        mos_delete_domain.sh $MXOS1_HOST_IP $MXOS1_PORT $domain
}

#create domain
curl -X PUT -v -d type=local http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/domain/v2/$domain
#Create User
curl -X PUT -v -d email=user1@$domain -d password=p -d cosId=default http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/user1@$domain
curl -X PUT -v -d email=user2@$domain -d password=p -d cosId=default http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/user2@$domain

#create folder
FOLDER=aaaa

testIMAP $user1name "create $FOLDER" "OK CREATE completed"

sleep 2

#shared folder
curl -X PUT -v -H "Content-Type: application/x-www-form-urlencoded" http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/$user1name/folders/$FOLDER/share/$user2name > put.log 2>&1

grep -i "HTTP/1.1 200 OK" put.log
if (( $? == 0 ));then
    log_pass "Shared folder successfully"
else
    log_fail "Shared folder failed"
fi

testIMAP $user1name "SELECT $FOLDER" "0 EXISTS"
testIMAP $user2name "SELECT $user1name-$FOLDER" "0 EXISTS"

#move use1 default message from INBOX to shared-folder
expect << EOF
spawn telnet $MX1_HOST $MX1_IMAP_PORT
expect "OK IMAP4 server"
send "a login $user1name $password\r"
expect "OK LOGIN completed"
send "a select INBOX\r"
expect "1 EXISTS"
send "a move 1 $FOLDER\r"
expect "MOVE completed"
send "a select $FOLDER\r"
expect "SELECT completed"
send "a logout\r"
expect "LOGOUT completed"
EOF


## verify message move
testIMAP $user1name "SELECT INBOX" "0 EXISTS"
testIMAP $user1name "SELECT $FOLDER" "1 EXISTS"
sleep 2
testIMAP $user2name "SELECT $user1name-$FOLDER" "1 EXISTS"

#move user2 default message from INBOX to shared-folder
expect << EOF
spawn telnet $MX1_HOST $MX1_IMAP_PORT
expect "OK IMAP4 server"
send "a login $user2name $password\r"
expect "OK LOGIN completed"
send "a select $user1name-$FOLDER\r"
expect "1 EXISTS"
send "a move 1 INBOX\r"
expect "MOVE completed"
send "a select INBOX\r"
expect "SELECT completed"
send "a logout\r"
expect "LOGOUT completed"
EOF

testIMAP $user2name "SELECT INBOX" "2 EXISTS"
testIMAP $user1name "SELECT $FOLDER" "0 EXISTS"
testIMAP $user2name "SELECT $user1name-$FOLDER" "0 EXISTS"

#UnSharedFolder
curl -X DELETE -v -H "Content-Type: application/x-www-form-urlencoded" http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/$user1name/folders/$FOLDER/share/$user2name > del.log 2>&1

grep -i "HTTP/1.1 200 OK" del.log
if (( $? == 0 ));then
    log_pass "unshared folder successfully"
else
    log_fail "unshared folder failed"
fi

#clean up
rm -rf imaplist.out
rm -rf put.log
rm -rf del.log
cleanup





