#!/bin/bash
# this test script is applicable to 
# MX-10019:Deliever message between AutoReplyStart and StopDate when both sets:Expect autoreply success 

#define accounts variables
id1=`echo $RANDOM`
user1=ar$id1
id2=`echo $RANDOM`
user2=ar$id2
autoreplymode=vacation

#define clean_account function
function clean_accounts ()
{
		echo "##########  doing some clear job ..."
		#delete accounts
		curl -s -X DELETE http://${MXOS1_HOST_IP}:$MXOS1__PORT/mxos/mailbox/v2/$user1@$defaultdomain  >/dev/null
		tmp1=$(curl -s -X GET http://${MXOS1_HOST_IP}:$MXOS1__PORT/mxos/mailbox/v2/$user1@$defaultdomain |grep "Mailbox does not exist"|wc -l)
		curl -s -X DELETE http://${MXOS1_HOST_IP}:$MXOS1__PORT/mxos/mailbox/v2/$user2@$defaultdomain  >/dev/null
		tmp2=$(curl -s -X GET http://${MXOS1_HOST_IP}:$MXOS1__PORT/mxos/mailbox/v2/$user2@$defaultdomain |grep "Mailbox does not exist"|wc -l)
		if [[ "$tmp1" -eq "1"  && "$tmp2" -eq "1" ]]
		then
		  echo -e "\033[32m##########  Accont deleted successfully\033[0m"
		  exit 100
		else
			echo -e "\033[31m##########  Accont deleted failed,PLease check manually,Exiting now ...\033[0m"
			exit 100
		fi
}

trap clean_accounts SIGHUP SIGINT SIGTERM

#1 clear mta.log and other tmp files
echo "########## 1 Clear mta.log using expect tool ..."
expect <<-EOF 
set timeout $expect_timeout	
spawn ssh imail2@${MX1_HOST_IP1}
expect  "*Password" { send "imail\r" }
expect  "*~" { send "> ~/log/mta.log\r" }
expect  "*~"
exit
EOF

#clear other tmp log files
rm expect*.log 
rm imapfetch*.log
rm send*.log
	
#2 create accounts user1@$defaultdomain and user2@$defaultdomain
echo "########## 2 Accounts provision ..."
tmp1=$(curl -s -X PUT -d "cosId=default&password=p" http://${MXOS1_HOST_IP}:$MXOS1__PORT/mxos/mailbox/v2/$user1@$defaultdomain)
echo $tmp1
expr $tmp1 + 0 &>/dev/null
tmp11=$(echo $?)
tmp2=$(curl -s -X PUT -d "cosId=default&password=p" http://${MXOS1_HOST_IP}:$MXOS1__PORT/mxos/mailbox/v2/$user2@$defaultdomain)
echo $tmp2
expr $tmp2 + 0 &>/dev/null
tmp22=$(echo $?)
let tmpv=tmp11+tmp22
if [[ "$tmpv" -eq "0" ]]
then
  echo -e "\033[32m########## 2 Accont provision successfully, we can continue now\033[0m"
else
	echo -e "\033[31m########## 2 Accont provision failed,PLease check manually,Exiting now ...\033[0m"
	clean_accounts
	exit 1
fi

#3 get currect epoch date ,and calaute the autoreplystartdate
expect <<-EOF 
set timeout $expect_timeout	
log_file expect.log 
spawn ssh root@${MX1_HOST_IP1}
expect  "*Password" { send "letmein\r" }
expect  "*~"  { send "date +%s\r\n" }
expect "*~"
exit
EOF

#cet:curent epoc time
cet=$(grep -A  1 "date +%s" expect.log |grep -v "date")
cet=$(echo ${cet:0:10})
#set autoreplystartdate 5s later, and autoreplystopdate 30 minutes later.
let autoreplystartdate=cet+5
let autoreplystopdate=cet+1800
sleep 5

#4 configure user2 to proper autoreply mode
echo "########## 4 Configure user2 to vacation autoreply mode using expect tool ..."
expect <<-EOF 
set timeout $expect_timeout	
log_file expect.log 
spawn ssh imail2@${MX1_HOST_IP1}
expect  "*Password" { send "imail\r" }
expect  "*~"  { send "echo 'internal:' >data.txt\r" }
expect  "*~"  { send "echo 'Vacation,This is an autoreply message for internal senders!' >>data.txt\r" }
expect  "*~"  { send "echo 'external:' >>data.txt\r" }
expect  "*~"  { send "echo 'Vacation,This is an external autoreply message for external senders!' >>data.txt\r" }
expect  "*~"  { send "autoreplyctrl ${user2}@$defaultdomain $autoreplymode data.txt $autoreplystartdate $autoreplystopdate\r" }
expect "*~"
exit
EOF

count=$(grep  -i "AutoReply data updated Successfully"  expect.log|wc -l)
if [[ "$count" -eq "1" ]];then
	echo -e "\033[32m##########4 Congifuration successfully\033[0m"
else
	echo -e "\033[31m##########4 Configuration failed,please check maunually!Exiting now ...\033[0m"
	clean_accounts
	exit 2
fi

# 5 deliever 1 message from user1 to user2, we expect that will have a autoreplied message in inbox of user1
echo "##########5 delieber 1 message from user1 to user2 ..."
#create message body
echo "Subject: test message about autoreply feature" >send.data
echo "To:$user2" >>send.data
echo >>send.data
echo "Vacation,This ia a wonderful world!!" >>send.data

sendmail.pl  $MX1_HOST_IP1 $MX1_SMTP_PORT $user1 $user2  <send.data >send.log 
count=$(grep "250 Message received" send.log|wc -l)
if [[ "$count" -eq "1" ]]
then
  echo -e "\033[32m########## 5 Message Deliver successfully, we can continue now\033[0m"
else
	echo -e "\033[31m########## 5 Message Deliver failed,please check manually,Exiting now ...\033[0m"
	cat send.log
	clean_accounts
	exit 3
fi

#6 check mta.log, make sure autoreply flag "autoreplied" exist:
echo "########## 6 Check mta.log using expect tool ..."
expect <<-EOF 
set timeout $expect_timeout	
log_file expect.log 
spawn ssh imail2@${MX1_HOST_IP1}
expect  "*Password" { send "imail\r" }
expect  "*~" { send "cat log/mta.log\r" }
expect  "*~"
exit
EOF

count=$(grep  -i "autoreplied"  expect.log|wc -l)
count1=$(grep -i "delivered" expect.log |wc -l)
if [[ "$count" -eq "1" && "$count1" -eq "2" ]];then
	echo -e "\033[32m##########6 Autoreply messaeg delievered successfully!!\033[0m"
else
	echo -e "\033[31m##########6 Autoreply messaeg delievered failed!Please check manually,Exiting now ...\033[0m"
	clean_accounts
	exit 4
fi 

#7 check autoreplied message in inbox of user1
echo "########## 7 check autoreplied message in inbox of user1 ..."
imapmail.pl   $MX1_HOST_IP1 $MX1_IMAP_PORT $user1 p inbox 2 >imapfetch.log
cat imapfetch.log
count=$(grep "Vacation,This is an autoreply message for internal senders!" imapfetch.log|wc -l)
count1=$(grep "Vacation,This ia a wonderful world!!" imapfetch.log|wc -l)
if [[ "$count" -eq	 "1" && "$count1" -eq "0" ]];then
		echo -e "\033[32m##########7 Check autoreplied messaege successfully!!\033[0m"
else
		echo -e "\033[31m##########7 Check autoreplied messaege failed!Please checl manually,Exiting now ...\033[0m"
		clean_accounts
		exit 5
fi

#8 clear mta.log 
echo "########## 8 Clear mta.log  ..."
expect <<-EOF 
set timeout $expect_timeout	
spawn ssh imail2@${MX1_HOST_IP1}
expect  "*Password" { send "imail\r" }
expect  "*~" { send "> ~/log/mta.log\r" }
expect  "*~"
exit
EOF

#9 deliever another 1 message from user1 to user2, we expect that will not have a autoreplied message 
echo "##########9 delieber 1 message from user1 to user2 ..."

sendmail.pl  $MX1_HOST_IP1 $MX1_SMTP_PORT $user1 $user2  <send.data >send2.log 
count=$(grep "250 Message received" send2.log|wc -l)
if [[ "$count" -eq "1" ]]
then
  echo -e "\033[32m########## 9 Message Deliver successfully, we can continue now\033[0m"
else
	echo -e "\033[31m########## 9 Message Deliver failed,please check manually,Exiting now ...\033[0m"
	cat send2.log
	clean_accounts
	exit 3
fi

#10 check mta.log, make sure autoreply flag "MtaAutoReplySuppressedAlreadySent" exist:
echo "########## 10 Check mta.log using expect tool ..."
expect <<-EOF 
set timeout $expect_timeout	
log_file expect.log 
spawn ssh imail2@${MX1_HOST_IP1}
expect  "*Password" { send "imail\r" }
expect  "*~" { send "cat log/mta.log\r" }
expect  "*~"
exit
EOF

count=$(grep  -i "MtaAutoReplySuppressedAlreadySent"  expect.log|wc -l)
if [[ "$count" -eq "1" ]];then
	echo -e "\033[32m##########10 Autoreply messaeg undelievered successfully!!\033[0m"
	log_pass "AutoReply in $autoreplymode mode with message delievered between start/stop date for internal sender test success!"
else
	echo -e "\033[31m##########10 Autoreply messaeg undelievered failed!Please check manually,Exiting now ...\033[0m"
	log_fail "AutoReply in $autoreplymode mode with message delievered between start/stop date for internal sender test failed!"
	clean_accounts
	exit 4
fi 

#delete all accounts if all works fine.
clean_accounts