#!/bin/bash

set -x

module="$1"
key="$2"
value="$3"
node="$4"

get_node_host()
{
    local node=$1
    for i in $(seq 1 10)
    do
        node_var="RG_SMTP${i}_NODE"
        if [ "${!node_var}" = "$node" ]; then
            var="RG_SMTP${i}_HOST" ; imail_hostname=${!var}
            var="RG_SMTP${i}_IMAIL_USER" ; imail_username=${!var}
            var="RG_SMTP${i}_OWM_COMMON_INSTALL" ; imail_path=${!var}
            var="RG_SMTP${i}_CONFSERV_HOST" ; short_host=${!var}
            return
        fi
    done
}

if [ "$RG_CONSOLE1_HOST" = "" ] || [ "$RG_CONSOLE1_HOST" = "nohost.invalid" ]; then
    ### Config DB mode
    get_node_host $node

    if [ ! -f $WORK_DIR/owm-configdb-lock ]; then
        ssh -o BatchMode=yes -o StrictHostKeyChecking=no $imail_username@$imail_hostname "$imail_path/bin/imconfcontrol -lockServer"
        echo $TC_NAME > $WORK_DIR/owm-configdb-lock
    fi

    ### Get the value

    hh=$(echo $key | cut -f 2 -d '/')
    mm=$(echo $key | cut -f 3 -d '/')
    kk=$(echo $key | cut -f 4 -d '/')

    previous=$(ssh -o BatchMode=yes -o StrictHostKeyChecking=no $imail_username@$imail_hostname "$imail_path/bin/imconfget -h $hh -m $mm $kk")

    if [ "$previous" = "" ]; then
        value="$value"
    else
        value="$previous\n$value"
    fi

    ### Set the value

    ssh -o BatchMode=yes -o StrictHostKeyChecking=no $imail_username@$imail_hostname "$imail_path/bin/imconfcontrol -install -nobroadcast -noRestarts -key \"$key=$value\""
fi
