#!/bin/bash

domain=$1

set -x

if [ "$domain" = "" ]; then
	exit 1
fi


if [ "$RG_CONSOLE1_HOST" = "" ] || [ "$RG_CONSOLE1_HOST" = "nohost.invalid" ]; then
        ##
        ## Config DB mode
        ##

        #Using MXOS
        if [ "$MXOS1_HOST_IP" != "" ]  &&  [ "$MXOS1_HOST_IP"  != "nohost.invalid" ]; then
                mos_create_domain.sh $MXOS1_HOST_IP $MXOS1_PORT $domain --relayhost $MX1_HOST_IP:$MX1_SMTP_PORT

                exit 0
        fi

        #Using MXLdap?
        if [ "$MX1_HOST_IP" != "" ]  &&  [ "$MX1_HOST_IP"  != "nohost.invalid" ]; then
                mx_create_domain.sh $MX1_USER $MX1_HOST_IP:$MX1_SSH_PORT $MX1_INSTALL $MX1_LDAP_PORT $domain --relayhost $MX1_HOST_IP:$MX1_SMTP_PORT

                exit 0
        fi

        echo "Neither MXOS1 or MX1 is set, at least one of them needs to be set."
        exit 2

else
        manager.pl $CPMS1_HOST $CPMS1_SMTP_MGMT_PORT $CPMS1_PASSWORD "GLOBAL DOMAIN ADD $domain" || failure
        manager.pl $CPMS1_HOST $CPMS1_SMTP_MGMT_PORT $CPMS1_PASSWORD "DOMAIN ADD $domain DSA=fred" || failure
fi


exit 0
