#!/bin/bash

namespace="$1"
rg_node="$2"

if [ "$namespace" = "" ]; then
    echo "Must specify namespace name"
    exit 1
fi

get_node_host()
{
    local node=$1
    for i in $(seq 1 10)
    do
        node_var="RG_SMTP${i}_NODE"
        if [ "${!node_var}" = "$node" ]; then
            var="RG_SMTP${i}_HOST" ; imail_hostname=${!var}
            var="RG_SMTP${i}_IMAIL_USER" ; imail_username=${!var}
            var="RG_SMTP${i}_INSTALL" ; policy_path="${!var}/mira/usr/store/policyrules/"
            return
        fi
    done
}


if [ "$RG_CONSOLE1_HOST" = "" ] || [ "$RG_CONSOLE1_HOST" = "nohost.invalid" ]; then
    ### Config DB mode 
	get_node_host $rg_node
    ssh -o BatchMode=yes -o StrictHostKeyChecking=no $imail_username@$imail_hostname "rm -rf $policy_path/$namespace ; mkdir -p $policy_path/$namespace"
else
    manager.pl $RG_CONSOLE1_HOST $RG_CONSOLE1_PORT $RG_CONSOLE1_PASSWORD "RGT POLICYBUILDER NAMESPACE SET $namespace"
fi
