#!/bin/bash

set -x

setting=$1
value=$2
node=$3

if [ "$RG_CONSOLE1_HOST" = "" ] || [ "$RG_CONSOLE1_HOST" = "nohost.invalid" ]
then
        rg_set_normal_setting "-" "custom-${setting}" "$value" "$node"
else
        if [ "$value" = "" ]; then
                manager.pl $RG_CONSOLE1_HOST $RG_CONSOLE1_PORT $RG_CONSOLE1_PASSWORD "RGT CUSTOM UNSET $setting NODE=$node"
        else
                manager.pl $RG_CONSOLE1_HOST $RG_CONSOLE1_PORT $RG_CONSOLE1_PASSWORD "RGT CUSTOM SET ${setting}=${value} NODE=$node"
        fi

        manager.pl $RG_CONSOLE1_HOST $RG_CONSOLE1_PORT $RG_CONSOLE1_PASSWORD "RGT CUSTOM GET NODE=$node"
fi

