#!/bin/bash

set -x

mxos_user=$1
mxos_host=$2
owm_common_root=$3
parameter=$4
value="$5"

ssh -o BatchMode=yes -o StrictHostKeyChecking=no ${mxos_user}@${mxos_host} "${owm_common_root}/bin/imconfcontrol -install -path ${owm_common_root}/config/config.db -key \"$parameter=$value\""

exit $?

