#!/bin/bash
# this test script is applicable to 
# MX-10284:Deliever message after AutoReplyStopDate when both sets::Expect autoreply failed

#define accounts variables
user1=ar$(echo $RANDOM)
user2=ar$(echo $RANDOM)

autoreplymode=reply

#define clean_account function
function clean_accounts ()
{
		echo "##########  doing some clear job ..."
		#delete accounts
		mos_delete_user.sh ${MXOS1_HOST_IP}  $MXOS1__PORT $user1@$defaultdomain
		mos_delete_user.sh ${MXOS1_HOST_IP}  $MXOS1__PORT $user2@$defaultdomain
}

trap clean_accounts SIGHUP SIGINT SIGTERM

#1 clear mta.log and other tmp files
echo "########## 1 Clear mta.log using expect tool ..."
expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"> ~/log/mta.log"

#clear other tmp log files
rm expect*.log 
rm imapfetch*.log
rm send*.log
	
#2 create accounts user1@$defaultdomain and user2@$defaultdomain
echo "########## 2 Accounts provision ..."
mos_create_user.sh  ${MXOS1_HOST_IP}  $MXOS1__PORT $user1@$defaultdomain $passwd
mos_create_user.sh  ${MXOS1_HOST_IP}  $MXOS1__PORT $user2@$defaultdomain $passwd

#3 get currect epoch date ,and calaute the autoreplystartdate
expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"date +%s"

#cet:curent epoc time
cet=$(grep -A  1 "date +%s" expect.log |grep -v "date")
cet=$(echo ${cet:0:10})
#set autoreplystartdate 5s later, and autoreplystopdate 30 minutes later.
let autoreplystartdate=cet+5
let autoreplystopdate=cet+10

#4 configure user2 to proper autoreply mode
echo "########## 4 Configure user2 to vacation autoreply mode using expect tool ..."

expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"echo 'internal:' >data.txt" \
"echo 'Reply,This is an autoreply message for internal senders!' >>data.txt" \
"echo 'external:' >>data.txt" \
"echo 'Reply,This is an external autoreply message for external senders!' >>data.txt" \
"autoreplyctrl ${user2}@$defaultdomain $autoreplymode data.txt $autoreplystartdate $autoreplystopdate"

count=$(grep  -i "AutoReply data updated Successfully"  expect.log|wc -l)
if [[ "$count" -eq "1" ]];then
	echo -e "\033[32m##########4 Congifuration successfully\033[0m"
else
	echo -e "\033[31m##########4 Configuration failed,please check maunually!Exiting now ...\033[0m"
	clean_accounts
	exit 2
fi

sleep 10

# 5 deliever 1 message from user1 to user2, we expect that will not have a autoreplied message in inbox of user1
echo "##########5 delieber 1 message from user1 to user2 ..."
#create message body
echo "Subject: test message about autoreply feature" >send.data
echo "To:$user2" >>send.data
echo >>send.data
echo "Reply,This ia a wonderful world!!" >>send.data

sendmail.pl  $MX1_HOST_IP1 $MX1_SMTP_PORT $user1 $user2  <send.data >send.log 
count=$(grep "250 Message received" send.log|wc -l)
if [[ "$count" -eq "1" ]]
then
  echo -e "\033[32m########## 5 Message Deliver successfully, we can continue now\033[0m"
else
	echo -e "\033[31m########## 5 Message Deliver failed,please check manually,Exiting now ...\033[0m"
	cat send.log
	clean_accounts
	exit 3
fi

#6 check mta.log, make sure autoreply flag "autoreplied" not exist:
echo "########## 6 Check mta.log using expect tool ..."
expect.exp $expect_timeout $MX1_HOST_IP1 $expect_user $expect_pass $expect_subuser \
"cat log/mta.log"

count=$(grep  -i "autoreplied"  expect.log|wc -l)
count1=$(grep -i "delivered" expect.log |wc -l)
if [[ "$count" -eq "0" && "$count1" -eq "1" ]];then
	echo -e "\033[32m##########6 Autoreply messaeg undelievered successfully!!\033[0m"
else
	echo -e "\033[31m##########6 Autoreply messaeg undelievered failed!Please check manually,Exiting now ...\033[0m"
	clean_accounts
	exit 4
fi 

#7 check autoreplied message in inbox of user1
echo "########## 7 check autoreplied message in inbox of user1 ..."
imapmail.pl   $MX1_HOST_IP1 $MX1_IMAP_PORT $user1 $passwd inbox 2 >imapfetch.log
cat imapfetch.log
count=$(grep "NO FETCH failed" imapfetch.log|wc -l)
if [[ "$count" -eq	 "1" ]];then
		echo -e "\033[32m##########7 Check autoreplied messaege not exist successfully!!\033[0m"
		log_pass "AutoReply in $autoreplymode mode with message delievered after start/stop date for internal sender test success!"
else
		echo -e "\033[31m##########7 Check autoreplied messaege not exist failed!Please checl manually,Exiting now ...\033[0m"
		log_fail "AutoReply in $autoreplymode mode with message delievered after start/stop date for internal sender test failed!"
		clean_accounts
		exit 5
fi

#delete all accounts if all works fine.
clean_accounts