#!/bin/bash

#APPEND testing in sharedFolder

domain=dom$$.dom
user1name=user1@$domain
user2name=user2@$domain
password=p

if [ "$MX1_HOST" = "nohost.invalid" ]; then
        log_skip "MX not installed"
fi

testIMAP()
{
username=$1
cmd=$2
./imaplist.pl ${MX1_HOST} ${MX1_IMAP_PORT} $username p "$cmd" > imaplist.out

shift
for key in "$@"
do
if grep "$key" imaplist.out
then
    echo "$cmd OK"
else
    cat imaplist.out
    failure "$cmd failed"
fi
done
}

cleanup()
{
        mos_delete_user.sh $MXOS1_HOST_IP $MXOS1_PORT $user1name
        mos_delete_user.sh $MXOS1_HOST_IP $MXOS1_PORT $user2name
        mos_delete_domain.sh $MXOS1_HOST_IP $MXOS1_PORT $domain
}

#create domain
curl -X PUT -v -d type=local http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/domain/v2/$domain
#Create User
curl -X PUT -v -d email=user1@$domain -d password=p -d cosId=default http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/user1@$domain
curl -X PUT -v -d email=user2@$domain -d password=p -d cosId=default http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/user2@$domain

#create folder
FOLDER=aaaa
testIMAP $user1name "create $FOLDER" "OK CREATE completed"

###test list
sleep 2
#shared folder
curl -X PUT -v -H "Content-Type: application/x-www-form-urlencoded" http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/$user1name/folders/$FOLDER/share/$user2name > put.log 2>&1

grep -i "HTTP/1.1 200 OK" put.log
if (( $? == 0 ));then
    log_pass "Shared folder successfully"
else
    log_fail "Shared folder failed"
fi

#Append message

DATA="Hello"
length=${#DATA}

testIMAP $user2name "SELECT $user1name-$FOLDER" "0 EXISTS"

exec 3<>/dev/tcp/$MX1_HOST_IP/$MX1_IMAP_PORT
    echo -en "a login $user2name p\r\n" >&3
    echo -en "a select $user1name-$FOLDER\r\n" >&3
    echo -en "a append $user1name-$FOLDER {$length}\r\n" >&3
    echo -en "$DATA\r\n" >&3
    echo -en "a logout\r\n" >&3
    touch imap-temp.log
    cat <&3 >imap-temp.log
    exec 3>&-

testIMAP $user2name "SELECT $user1name-$FOLDER" "1 EXISTS"

#UnSharedFolder
curl -X DELETE -v -H "Content-Type: application/x-www-form-urlencoded" http://$MXOS1_HOST_IP:$MXOS1_PORT/mxos/mailbox/v2/$user1name/folders/$FOLDER/share/$user2name > del.log 2>&1

grep -i "HTTP/1.1 200 OK" del.log
if (( $? == 0 ));then
    log_pass "Unshared folder successfully"
else
    log_fail "Unshared folder failed"
fi

#clean up
rm -rf imaplist.out
rm -rf put.log
rm -rf del.log
rm -rf imap-temp.log
cleanup




