#!/bin/bash


#Result=1_by_fefault
Result=1
#create test account

#body preview key enable	
set_config_keys "/*/common/enableXFIRSTLINE" "true"

Sanityuser=test$(echo $RANDOM)
account_create_fn $Sanityuser

imboxstats $Sanityuser@openwave.com &>accountexist.tmp
ec=$(grep -i "Unable to get mailbox" accountexist.tmp |wc -l)
if [ "$ec" -eq 1 ];then
	account_create_fn $Sanityuser
fi

immsgdelete  $Sanityuser@openwave.com  -all 


# Running Test.sh

#deliever 2 messages  ro mailbox
$smpl    -u  $Sanityuser@openwave.com -c 2   empty_body.txt
imap_fetch "$Sanityuser" "1:2" "firstline"     
firstlinedata_count=`grep "FETCH (FIRSTLINE (\"\")"   imapfetch.tmp |wc -l`
echo "firstlinedata_count=$firstlinedata_count"  >>$debuglog
echo "Result=$Result"  >>$debuglog
if [ $firstlinedata_count -eq 2 -a $Result -eq 0 ];then
	prints "IMAP:Body_preview_empty_body test successfully!"  "IMAP:Body_preview_empty_body"  2
	Result=0
else
	prints "IMAP:Body_preview_empty_body test failed!"  "IMAP:Body_preview_empty_body"  1
  	Result=1
fi
summary "IMAP:Body_preview_empty_body" $Result

# Running Cleanup.sh
#delete test acocunt
account_delete_fn $Sanityuser


#body preview key disable	
set_config_keys "/*/common/enableXFIRSTLINE" "false"

