#!/bin/bash


#Result=1_by_fefault
Result=1

#body preview key enable	
set_config_keys "/*/common/enableXFIRSTLINE" "true"

#create test account
Sanityuser=test$(echo $RANDOM)
account_create_fn $Sanityuser

imboxstats $Sanityuser@openwave.com &>accountexist.tmp
ec=$(grep -i "Unable to get mailbox" accountexist.tmp |wc -l)
if [ "$ec" -eq 1 ];then
	account_create_fn $Sanityuser
fi


immsgdelete  $Sanityuser@openwave.com  -all 


# Running Test.sh


#deliever 5 messages  ro mailbox
$smpl    -u  $Sanityuser@openwave.com -c 6   UTF8_body_less_than_80_CTE_7bit.txt
imap_fetch "$Sanityuser" "1,3,5" "firstline"     
firstlinedata_count=`grep "، ويمكن تح No body! いくつにな  我们是中国人， \")"   imapfetch.tmp |wc -l`
echo "########## firstlinedata_count=$firstlinedata_count"  >>debug.log
echo "########## Result=$Result"  >>debug.log
if [ $firstlinedata_count -eq 3 -a $Result -eq 0 ];then
	prints "IMAP:Body_preview_UTF8_body_less_than_80_CTE_7bit_multiple test successfully!"  "IMAP:Body_preview_UTF8_body_less_than_80_CTE_7bit_multiple"  2
	Result=0
else
  prints "IMAP:Body_preview_UTF8_body_less_than_80_CTE_7bit_multiple test failed!"  "IMAP:Body_preview_UTF8_body_less_than_80_CTE_7bit_multiple"  1
  Result=1
fi
summary "IMAP:Body_preview_UTF8_body_less_than_80_CTE_7bit_multiple" $Result

# Running Cleanup.sh
#delete test acocunt
account_delete_fn $Sanityuser

#body preview key disable	
set_config_keys "/*/common/enableXFIRSTLINE" "false"

